-- TradeLog: スクールレッスン本文にビジュアル要素 (図解 + インフォボックス + ハイライト) を追加
--
-- カスタム記法:
--   :::tip / :::warning / :::key / :::example で始まり、:::  で終わるブロック
--   :::diagram:NAME:::  で図解 (candlestick, currency_flow, pip_calculation,
--                                order_types, spread, support_resistance, lot_size)
--   `バッククォート` でキーワードを薄いアクセント背景でハイライト
--
-- 既存のレッスン content_ja / content_en を UPDATE する (idempotent)

-- ============================================================================
-- FX Basics: What is Forex?
-- ============================================================================

update public.school_lessons
   set content_ja = E'FX（Foreign Exchange）は外国為替証拠金取引の略称です。2つの通貨を売買することで為替差益を狙う取引で、世界最大の金融市場です。\n\n:::key\nFX市場の1日の取引量は約7兆ドル。株式市場の数十倍の規模で、世界中の銀行・機関投資家・個人トレーダーが参加しています。\n:::\n\n## なぜFXが人気なのか\n\nFX市場の魅力は主に3つあります。\n\n**24時間取引できる** — 月曜早朝（東京時間6:00頃）から土曜早朝まで、市場は常に開いています。東京→ロンドン→ニューヨークと、世界の主要市場が順番に開くため、自分のライフスタイルに合わせて取引できます。\n\n**少額から始められる** — `レバレッジ`という仕組みにより、実際の資金の何倍もの取引が可能です。日本のFX業者では最大25倍のレバレッジが使えます。つまり4万円の資金で100万円分の取引ができます。\n\n**上がっても下がっても利益を狙える** — 株式は基本的に「買い」から入りますが、FXでは「売り」からも取引を始められます。円高でも円安でも、方向を当てれば利益になります。\n\n## FXの基本的な仕組み\n\nFXは常に2つの通貨をペアで取引します。例えば USD/JPY（ドル円）の場合：\n\n- **買い（ロング）**: ドルを買って円を売る → ドル高（円安）になれば利益\n- **売り（ショート）**: ドルを売って円を買う → ドル安（円高）になれば利益\n\n:::example\n1ドル=150円の時にドルを1万通貨買い、152円で売った場合：(152 - 150) × 10,000 = 20,000円の利益\n:::\n\n## FXのリスク\n\n:::warning\n利益を大きくできるレバレッジは、損失も同様に拡大させます。資金管理とリスク管理を学ばずにトレードを始めると、短期間で資金を失う可能性があります。\n:::\n\nこのスクールでは、リスクを理解した上で適切にトレードする方法を学んでいきます。',
       content_en = E'FX (Foreign Exchange) is the trading of currency pairs to profit from exchange rate movements. It is the world''s largest financial market.\n\n:::key\nThe FX market trades approximately $7 trillion daily — many times larger than the stock market. Banks, institutions, and individual traders participate worldwide.\n:::\n\n## Why FX is Popular\n\n**24-hour trading** — From Sunday evening to Friday evening (EST), the market is always open. As Tokyo, London, and New York sessions overlap, you can trade around your schedule.\n\n**Start with small capital** — `Leverage` allows you to control large positions with relatively small capital. With 50:1 leverage, $2,000 can control $100,000 in trades.\n\n**Profit in any direction** — Unlike stocks, you can easily short-sell in FX. Whether the market goes up or down, you can profit if you predict the direction correctly.\n\n## How FX Works\n\nFX always involves trading two currencies as a pair. For example, with EUR/USD:\n\n- **Buy (Long)**: Buy euros, sell dollars → Profit if EUR strengthens\n- **Sell (Short)**: Sell euros, buy dollars → Profit if EUR weakens\n\n:::example\nBuy 10,000 USD/JPY at 150.00, sell at 152.00: (152 - 150) × 10,000 = ¥20,000 profit\n:::\n\n## FX Risks\n\n:::warning\nThe same leverage that amplifies profits also amplifies losses. Without proper risk management, you can lose your capital quickly.\n:::\n\nThis school will teach you how to trade responsibly with proper risk management.'
 where title_en = 'What is Forex?';

-- ============================================================================
-- FX Basics: How Currency Pairs Work
-- ============================================================================

update public.school_lessons
   set content_ja = E'通貨ペアはFX取引の基本単位です。どの通貨を買い、どの通貨を売るかを示します。\n\n## 通貨ペアの読み方\n\n:::diagram:currency_flow:::\n\nUSD/JPY = 150.00 の場合：\n- **左側（USD）**= `基軸通貨`（Base Currency）\n- **右側（JPY）**= `決済通貨`（Quote Currency）\n- **150.00** = 1ドルを買うのに150円が必要\n\n:::tip\n価格が上がる＝基軸通貨が強くなる、価格が下がる＝基軸通貨が弱くなる、と覚えてください。\n:::\n\n## 主要な通貨ペア（メジャーペア）\n\n取引量が多く、スプレッドが狭い主要ペアを覚えましょう：\n\n**USD/JPY（ドル円）** — 日本のトレーダーに最も人気。値動きが比較的安定しており、初心者向き。東京時間に活発に動きます。\n\n**EUR/USD（ユーロドル）** — 世界で最も取引量が多いペア。ロンドン〜ニューヨーク時間に活発。トレンドが出やすい特徴があります。\n\n**GBP/USD（ポンドドル）** — ボラティリティ（値動きの大きさ）が大きく、短時間で大きな利益も損失も出やすいペア。中〜上級者向き。\n\n**AUD/USD（豪ドルドル）** — 資源国通貨。原油や金の価格に影響を受けやすいです。\n\n## 通貨の強弱\n\nそれぞれの通貨には「強さ」があり、経済指標や金利政策によって日々変化します。\n\n:::key\n金利が高い通貨は買われやすく（USD, GBP, AUD）、安全資産とされる通貨（JPY, CHF）はリスクオフ時に買われる傾向があります。\n:::\n\n## 初心者へのアドバイス\n\n:::tip\n最初は1〜2ペアに絞って取引しましょう。USD/JPY は値動きの感覚をつかむのに最適です。複数のペアを同時に見ると混乱しやすいので、慣れるまでは集中が大切です。\n:::',
       content_en = E'Currency pairs are the foundation of FX trading. They show which currency you buy and which you sell.\n\n## Reading Currency Pairs\n\n:::diagram:currency_flow:::\n\nEUR/USD = 1.0850 means:\n- **Left (EUR)** = `Base Currency`\n- **Right (USD)** = `Quote Currency`\n- **1.0850** = 1 euro costs 1.0850 dollars\n\n:::tip\nPrice going up = base currency getting stronger. Price going down = base currency getting weaker.\n:::\n\n## Major Pairs\n\n**EUR/USD** — Most traded pair globally. Trends well during London and New York sessions.\n\n**USD/JPY** — Popular with Asian traders. Relatively stable, good for beginners.\n\n**GBP/USD** — High volatility. Can move fast in either direction. Better for intermediate traders.\n\n**AUD/USD** — Commodity-linked. Influenced by gold and oil prices.\n\n## Currency Strength\n\n:::key\nHigher interest rate currencies tend to attract buyers (USD, GBP, AUD), while safe-haven currencies (JPY, CHF) strengthen during risk-off events.\n:::\n\n## Beginner Tip\n\n:::tip\nStart with 1-2 pairs. USD/JPY or EUR/USD are ideal for learning. Avoid watching too many pairs at once — focus is key when starting out.\n:::'
 where title_en = 'How Currency Pairs Work';

-- ============================================================================
-- FX Basics: Pips and Lots
-- ============================================================================

update public.school_lessons
   set content_ja = E'FXの損益を語る上で欠かせない単位が`pips`と`ロット`です。\n\n## pips（ピップス）とは\n\npipsは為替レートの最小変動単位です。\n\n:::diagram:pip_calculation:::\n\n**ほとんどの通貨ペア**: 小数点以下第4位が1pip\n- EUR/USD: 1.0850 → 1.0851 = **1pip上昇**\n- EUR/USD: 1.0850 → 1.0860 = **10pips上昇**\n\n**JPY絡みのペア**: 小数点以下第2位が1pip\n- USD/JPY: 150.00 → 150.01 = **1pip上昇**\n- USD/JPY: 150.00 → 150.50 = **50pips上昇**\n\n:::tip\n金額ではなくpipsで成績を測ることで、ロットサイズに関係なくトレードの質を比較できます。100pips獲得したトレーダーは、ロットサイズに関わらず「同じ質のトレード」をしたと言えます。\n:::\n\n## ロット（Lot）とは\n\nロットは取引数量の単位です。\n\n:::diagram:lot_size:::\n\n## 損益の計算\n\n:::example\nUSD/JPYを0.1ロットで買い、20pips上昇した場合：\n0.1ロット × 20pips × 約100円/pip = 約2,000円の利益\n:::\n\n:::example\nEUR/USDを1ロットで売り、15pips下落した場合：\n1ロット × 15pips × 約$10/pip = 約$150の利益\n:::\n\n## 初心者のロットサイズ\n\n:::warning\n資金10万円の場合、0.01〜0.05ロットから始めることを強く推奨します。1回のトレードで資金の2%以上をリスクにさらさないのが鉄則です。\n:::\n\n- 資金10万円 → 1トレードの最大損失 = 2,000円\n- 0.01ロットなら、200pips逆行しても2,000円の損失\n- 0.1ロットなら、20pips逆行で2,000円の損失\n\n:::key\nロットサイズは「守りの武器」です。小さく始めて、勝ちパターンが見つかったら少しずつ増やしましょう。\n:::',
       content_en = E'`Pips` and `lots` are essential units for measuring profits and trade sizes in FX.\n\n## What is a Pip?\n\nA pip is the smallest standard price movement in a currency pair.\n\n:::diagram:pip_calculation:::\n\n**Most pairs**: The 4th decimal place\n- EUR/USD: 1.0850 → 1.0851 = **1 pip**\n\n**JPY pairs**: The 2nd decimal place\n- USD/JPY: 150.00 → 150.01 = **1 pip**\n\n:::tip\nPips measure trade quality regardless of position size. A trader who captures 100 pips made an equally good trade whether they used 0.01 or 10 lots.\n:::\n\n## What is a Lot?\n\nA lot is the unit of trade size.\n\n:::diagram:lot_size:::\n\n## Profit Calculation\n\n:::example\nBuy USD/JPY at 0.1 lot, price rises 20 pips:\n0.1 lot × 20 pips × ~$1/pip = ~$20 profit\n:::\n\n## Beginner Lot Size\n\n:::warning\nWith $1,000 capital, start with 0.01-0.05 lots. Never risk more than 2% of your account on a single trade.\n:::\n\n:::key\nSmall lots are your shield while you learn. Start small, increase only after finding your winning patterns.\n:::'
 where title_en = 'Pips and Lots';

-- ============================================================================
-- FX Basics: Order Types
-- ============================================================================

update public.school_lessons
   set content_ja = E'FXには複数の注文方法があります。場面に応じて使い分けることで、より戦略的なトレードが可能になります。\n\n:::diagram:order_types:::\n\n## 成行注文（Market Order）\n\n今の価格ですぐに売買する注文です。\n\n:::tip\n使う場面: 今すぐエントリーしたい時、明確なシグナルが出た時。スプレッド分だけ不利な価格で約定することがある点に注意。\n:::\n\n## 指値注文（Limit Order）\n\n指定した価格に達したら自動で注文を出す仕組みです。\n\n**買い指値（Buy Limit）**: 現在価格より安い価格を指定\n- 例: USD/JPY が150.50の時、150.00で買い指値 → 150.00まで下がったら自動で買い\n\n**売り指値（Sell Limit）**: 現在価格より高い価格を指定\n- 例: USD/JPY が150.00の時、150.50で売り指値 → 150.50まで上がったら自動で売り\n\n:::example\n「押し目買い」「戻り売り」を狙う時に使います。チャートの前で待つ必要がなくなります。\n:::\n\n## 逆指値注文（Stop Order）\n\n指定した価格を超えたら注文を出す仕組みです。`ブレイクアウト`戦略で使います。\n\n**買い逆指値（Buy Stop）**: 現在価格より高い価格を指定\n- 例: レジスタンスライン151.00を超えたら買い\n\n**売り逆指値（Sell Stop）**: 現在価格より低い価格を指定\n- 例: サポートライン149.00を割ったら売り\n\n## ストップロス（Stop Loss / 損切り注文）\n\n:::warning\n最も重要な注文です。損失を限定するために、エントリーと同時に必ず設定しましょう。ストップロスなしのトレードは絶対にしないでください。\n:::\n\n- 買いポジション: 現在価格より下に設定\n- 売りポジション: 現在価格より上に設定\n\n:::example\nUSD/JPY を150.00で買い、149.70にストップロス設定 → 30pipsの損失で自動決済。予想外の急落でも損失はこの範囲に収まります。\n:::\n\n## テイクプロフィット（Take Profit / 利確注文）\n\n利益を確定させる注文です。目標価格に達したら自動で決済します。\n\n## 注文の組み合わせ（OCO注文）\n\n:::key\n基本セット: エントリー + ストップロス + テイクプロフィット。この3点セットを毎回のトレードで必ず設定する癖をつけましょう。プロトレーダーでもこの基本は変わりません。\n:::',
       content_en = E'FX offers several order types. Using them strategically improves your trading significantly.\n\n:::diagram:order_types:::\n\n## Market Order\n\nBuy or sell immediately at the current price.\n\n:::tip\nUse when you want instant execution after a clear signal. Note that you may get a slightly different price due to the spread.\n:::\n\n## Limit Order\n\nAutomatically executes at a specified price.\n\n- **Buy Limit**: Set below current price (buy on a dip)\n- **Sell Limit**: Set above current price (sell on a rally)\n\n:::example\nUse limit orders for "buy the dip" or "sell the rally" strategies. No need to watch the chart constantly.\n:::\n\n## Stop Order\n\nTriggers when price breaks through a level. Used for `breakout` strategies.\n\n- **Buy Stop**: Set above current price (buy on breakout)\n- **Sell Stop**: Set below current price (sell on breakdown)\n\n## Stop Loss (Most Important!)\n\n:::warning\nAlways set a stop loss with every trade. Trading without a stop loss is gambling, not trading. It limits your losses to a predetermined amount.\n:::\n\n:::example\nBuy USD/JPY at 150.00, set stop at 149.70 = max 30 pip loss. Even if a flash crash occurs, your loss is capped.\n:::\n\n## Take Profit\n\nLocks in your gains. Automatically closes at your target price.\n\n## The Essential Trio\n\n:::key\nEvery trade should have: Entry + Stop Loss + Take Profit. Make this a habit from day one. Even professional traders never skip this.\n:::'
 where title_en = 'Order Types';

-- ============================================================================
-- FX Basics: Spreads and Swaps
-- ============================================================================

update public.school_lessons
   set content_ja = E'`スプレッド`と`スワップ`は、FX取引にかかるコストです。利益を出すためには、まずこのコストを理解する必要があります。\n\n## スプレッドとは\n\nスプレッドは「買値（Ask）」と「売値（Bid）」の差です。FX業者の主な収入源であり、トレーダーにとっての取引コストです。\n\n:::diagram:spread:::\n\n:::key\n買った瞬間にスプレッド分のマイナスからスタートします。利益を出すには、まずスプレッド分を超える値動きが必要です。\n:::\n\n## スプレッドの目安\n\n主要ペアの一般的なスプレッド:\n- **USD/JPY**: 0.2〜1.0 pips\n- **EUR/USD**: 0.3〜1.0 pips\n- **GBP/USD**: 0.6〜2.0 pips\n- **GBP/JPY**: 1.0〜3.0 pips\n\n:::warning\nスプレッドは固定ではありません。早朝（流動性が低い時間帯）、重要な経済指標の発表前後、年末年始やクリスマスには大幅に広がることがあります。\n:::\n\n## スキャルピングとスプレッド\n\n:::example\n数pipsの利益を狙うスキャルピングでは、スプレッドの影響が非常に大きくなります。スプレッドが0.3pipsと1.0pipsでは、100回取引すると70pipsもの差が出ます。\n:::\n\n## スワップとは\n\nスワップは通貨ペア間の`金利差`から生じる損益です。ポジションを翌日に持ち越す（オーバーナイト）と発生します。\n\n**プラススワップ**: 金利の高い通貨を買い、低い通貨を売ると受け取れる\n- 例: USD/JPY買い → 米ドル金利(高) - 円金利(低) = プラス\n\n**マイナススワップ**: 金利の低い通貨を買い、高い通貨を売ると支払う\n- 例: USD/JPY売り → 円金利(低) - 米ドル金利(高) = マイナス\n\n:::tip\n水曜日は3日分のスワップが付きます（土日分を含むため）。デイトレードやスキャルピングならスワップの影響は小さいですが、スイングトレード（数日〜数週間保有）ではスワップも考慮しましょう。\n:::\n\n## コストを最小限にするために\n\n1. スプレッドの狭い時間帯に取引する（東京〜ロンドン重複時間: 16:00〜19:00）\n2. 重要指標発表の直前直後は避ける\n3. マイナススワップが大きいポジションの長期保有は避ける\n4. 取引する通貨ペアのスプレッドを事前に確認する',
       content_en = E'`Spreads` and `swaps` are the costs of FX trading. Understanding these costs is essential for profitability.\n\n## What is a Spread?\n\nThe spread is the difference between the Ask (buy) and Bid (sell) price. It is the broker''s main revenue and your trading cost.\n\n:::diagram:spread:::\n\n:::key\nYou start every trade at a loss equal to the spread. Price must move in your favor beyond the spread before you profit.\n:::\n\n## Typical Spreads\n\n- **EUR/USD**: 0.3–1.0 pips\n- **USD/JPY**: 0.2–1.0 pips\n- **GBP/USD**: 0.6–2.0 pips\n\n:::warning\nSpreads are not fixed. They widen during low liquidity (early morning), around major news events, and during holidays.\n:::\n\n## Scalping and Spreads\n\n:::example\nFor scalpers targeting a few pips per trade, the spread impact is huge. A difference of 0.3 vs 1.0 pips over 100 trades = 70 pips lost to spreads.\n:::\n\n## What is a Swap?\n\nSwaps are overnight interest charges based on the `interest rate differential` between the two currencies.\n\n- **Positive swap**: Earn when buying the higher-rate currency\n- **Negative swap**: Pay when buying the lower-rate currency\n\n:::tip\nWednesday swaps are triple (covering Saturday and Sunday). Day traders rarely worry about swaps, but swing traders should factor them in.\n:::\n\n## Minimizing Costs\n\n1. Trade during active sessions (London-NY overlap)\n2. Avoid trading around major news releases\n3. Be mindful of negative swaps on long-term positions\n4. Always check current spreads before entering'
 where title_en = 'Spreads and Swaps';

-- ============================================================================
-- Technical Analysis: Complete Candlestick Guide
-- ============================================================================

update public.school_lessons
   set content_ja = E'ローソク足はチャート分析の最も基本的なツールです。1本のローソク足から、相場の力関係を読み取れます。\n\n## ローソク足の構造\n\n:::diagram:candlestick:::\n\nローソク足は4つの価格で構成されます：\n- **始値（Open）**: その期間の最初の価格\n- **高値（High）**: 最も高かった価格（上ヒゲの先端）\n- **安値（Low）**: 最も低かった価格（下ヒゲの先端）\n- **終値（Close）**: その期間の最後の価格\n\n**陽線（緑/白）**: 終値 > 始値 → 上昇で終わった\n**陰線（赤/黒）**: 終値 < 始値 → 下落で終わった\n\n## 重要なローソク足パターン\n\n### 単体パターン\n\n**大陽線（Marubozu）** — 長い実体でヒゲがほとんどない。強い買い圧力を示す。\n\n**大陰線** — 長い実体でヒゲがほとんどない。強い売り圧力を示す。\n\n**ピンバー（Pin Bar）** — 実体が小さく、片方のヒゲが非常に長い。ヒゲの方向への反転シグナル。\n\n:::tip\n長い下ヒゲのピンバー → 下落からの反転（買いシグナル）。長い上ヒゲのピンバー → 上昇からの反転（売りシグナル）。\n:::\n\n**十字線（Doji）** — 始値と終値がほぼ同じ。売り買いが拮抗しており、トレンド転換の可能性。\n\n### 複合パターン\n\n**包み足（Engulfing）** — 2本目のローソク足が1本目を完全に包み込むパターン。\n\n:::key\n強気包み足: 陰線の後に大きな陽線 → 上昇転換。弱気包み足: 陽線の後に大きな陰線 → 下落転換。サポート/レジスタンス上で出現すると信頼度が高い。\n:::\n\n**はらみ足（Harami）** — 包み足の逆で、2本目が1本目の中に収まるパターン。トレンドの勢い低下を示す。\n\n**明けの明星（Morning Star）** — 3本のローソク足。陰線→小さな実体→陽線。底打ちシグナル。\n\n**宵の明星（Evening Star）** — 3本のローソク足。陽線→小さな実体→陰線。天井シグナル。\n\n## ローソク足を使うコツ\n\n:::warning\n1つのパターンだけで判断しないでください。必ず「どこで出たか」（文脈）と「上位足の方向」を確認しましょう。\n:::\n\n1. **単体ではなく文脈で見る**: サポートライン上のピンバーは強いシグナル、何もない所のピンバーはノイズ\n2. **上位足で確認する**: 5分足のシグナルは弱い、4時間足や日足のシグナルは信頼度が高い\n3. **出来高（ボリューム）と合わせる**: 大きな出来高を伴うパターンは信頼性が高い\n4. **他のテクニカル指標と組み合わせて使う**',
       content_en = E'Candlesticks are the most fundamental charting tool. Each candle tells a story about the battle between buyers and sellers.\n\n## Candlestick Structure\n\n:::diagram:candlestick:::\n\nEach candle has four prices: Open, High, Low, Close.\n\n**Bullish (green/white)**: Close > Open — buyers won\n**Bearish (red/black)**: Close < Open — sellers won\n\n## Key Single Patterns\n\n**Marubozu** — Long body, no wicks. Strong momentum.\n\n**Pin Bar** — Small body, long wick. Reversal signal in the direction opposite the long wick.\n\n:::tip\nLong lower wick pin bar = bullish reversal signal. Long upper wick pin bar = bearish reversal signal.\n:::\n\n**Doji** — Open and close nearly equal. Indecision, potential reversal.\n\n## Key Multi-Candle Patterns\n\n**Engulfing** — Second candle completely engulfs the first.\n\n:::key\nBullish engulfing: bearish candle followed by larger bullish candle → reversal up. Most reliable when it appears at support/resistance levels.\n:::\n\n**Morning Star / Evening Star** — Three-candle reversal patterns at bottoms and tops.\n\n## Tips\n\n:::warning\nNever trade based on a single pattern alone. Always check WHERE it appeared (context) and the higher timeframe direction.\n:::\n\n1. Context matters more than the pattern itself\n2. Higher timeframes give more reliable signals\n3. Combine with other indicators for confirmation'
 where title_en = 'Complete Candlestick Guide';

-- ============================================================================
-- Technical Analysis: Support & Resistance in Practice
-- ============================================================================

update public.school_lessons
   set content_ja = E'`サポート`（支持線）と`レジスタンス`（抵抗線）は、テクニカル分析の土台です。\n\n:::diagram:support_resistance:::\n\n## サポートとは\n\n価格が下落した時に、反発して上昇しやすいライン。過去に何度も買いが入った価格帯です。\n\n## レジスタンスとは\n\n価格が上昇した時に、反落しやすいライン。過去に何度も売りが入った価格帯です。\n\n## 引き方の基本\n\n1. チャートを日足や4時間足にする\n2. 価格が2回以上反発した水平ラインを引く\n3. ピンポイントの「線」ではなく「ゾーン（帯）」として捉える\n4. より多くの反発回数があるラインほど強い\n\n:::key\nサポート/レジスタンスは「線」ではなく「ゾーン」です。数pipsの誤差は常にあるので、帯として捉える方が実践的です。\n:::\n\n## ロールリバーサル\n\n:::tip\n最も重要な概念の一つ。サポートを下に割ると、そのラインは新しいレジスタンスに変わります。逆も同様です。\n:::\n\n:::example\nUSD/JPY の150.00がサポートだったが下抜け → 次に150.00まで戻った時に売りが入りやすい（レジスタンスとして機能）。これが「ロールリバーサル」です。\n:::\n\n## 実践的なエントリー方法\n\n**サポートでの買い**:\n1. サポートゾーンまで価格が下落\n2. ローソク足の反転パターン（ピンバー等）を確認\n3. ストップロスはサポートの少し下\n4. テイクプロフィットは次のレジスタンス\n\n**レジスタンスでの売り**:\n1. レジスタンスゾーンまで価格が上昇\n2. 反転パターンを確認\n3. ストップロスはレジスタンスの少し上\n4. テイクプロフィットは次のサポート\n\n## よくある間違い\n\n:::warning\nラインを引きすぎないでください。重要なラインだけに絞ることが大切です。また、1回しか反発していないラインは信頼性が低いので注意しましょう。\n:::\n\n- 正確な価格にこだわりすぎる（ゾーンで考える）\n- 上位足のサポレジを無視して下位足だけで判断する',
       content_en = E'`Support` and `resistance` are the foundation of technical analysis.\n\n:::diagram:support_resistance:::\n\n## Support\n\nA price level where buying pressure tends to emerge, preventing further decline. These are prices where buyers have stepped in multiple times before.\n\n## Resistance\n\nA price level where selling pressure tends to emerge, preventing further advance. These are prices where sellers have stepped in before.\n\n## How to Draw\n\n1. Use daily or 4-hour charts\n2. Find levels where price bounced at least twice\n3. Think in zones, not exact lines\n4. More touches = stronger level\n\n:::key\nSupport and resistance are ZONES, not exact lines. There is always a margin of a few pips, so think in bands rather than precise prices.\n:::\n\n## Role Reversal\n\n:::tip\nOne of the most important concepts: when support breaks, it becomes resistance (and vice versa).\n:::\n\n:::example\nUSD/JPY 150.00 was support but broke down → next time price returns to 150.00, it acts as resistance with sellers stepping in. This is called "role reversal."\n:::\n\n## Practical Entry\n\n**Buy at support**: Wait for reversal candle pattern + set stop below the zone.\n**Sell at resistance**: Wait for reversal candle pattern + set stop above the zone.\n\n## Common Mistakes\n\n:::warning\nDon''t draw too many lines. Focus only on the most significant levels. Lines with only one touch are unreliable.\n:::'
 where title_en = 'Support & Resistance in Practice';
